# Generated by Django 4.0.2 on 2022-06-03 06:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.CharField(max_length=70)),
                ('taskName', models.CharField(max_length=70)),
                ('taskType', models.CharField(max_length=70)),
                ('uniqid', models.UUIDField(default=uuid.UUID('a0f98ebe-95a4-40c3-88a0-b300e52479ac'), editable=False, unique=True)),
                ('status', models.IntegerField(default=0)),
                ('task_card_uniqid', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMonitor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('taskuniqid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('resourceUniqid', models.CharField(default=django.contrib.auth.models.User, max_length=10)),
                ('status', models.CharField(default='not started', max_length=255)),
                ('endTime', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
