# Generated by Django 4.0.2 on 2022-06-03 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0003_alter_task_uniqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskId',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_card_uniqid',
        ),
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('3b233df2-9ef5-4061-8c71-9f41da56428c'), editable=False, unique=True),
        ),
    ]
