# Generated by Django 4.0.6 on 2022-07-06 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0006_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('b24e52a8-ebd4-48fd-9f02-1c3b98901cd0'), editable=False, unique=True),
        ),
    ]
