# Generated by Django 4.0.6 on 2022-07-07 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0007_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('c0ed7d81-3c6c-406b-af33-2f2492f48702'), editable=False, unique=True),
        ),
    ]
