# Generated by Django 4.0.6 on 2022-07-12 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0009_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('44cad2a0-250c-46e9-98c2-cf3d00695dd8'), editable=False, unique=True),
        ),
    ]
