# Generated by Django 4.0.6 on 2022-07-24 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0010_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('cd352710-41fd-40a5-adbf-193d5146db0b'), editable=False, unique=True),
        ),
    ]
