# Generated by Django 4.0.6 on 2022-07-24 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0011_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('d2c7b8ad-2cc2-4d75-be88-852bbd0ee253'), editable=False, unique=True),
        ),
    ]
