# Generated by Django 4.0.6 on 2022-08-02 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0012_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('fd648673-2b67-45eb-be1a-71bafd2bb4ab'), editable=False, unique=True),
        ),
    ]
