# Generated by Django 4.0.6 on 2022-08-02 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0013_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('ff261ce6-ea47-4ab1-ab10-5eb66bdf24cc'), editable=False, unique=True),
        ),
    ]
