# Generated by Django 4.0.6 on 2022-08-02 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0014_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('3dc3e99e-221a-4e5e-9f95-20f2d003c498'), editable=False, unique=True),
        ),
    ]
