# Generated by Django 4.0.6 on 2022-08-02 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0015_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('f5ffb67f-7768-4541-b12a-463685203c13'), editable=False, unique=True),
        ),
    ]
