# Generated by Django 4.0.6 on 2022-08-07 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0016_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('b08a1c5b-3e27-4822-b74f-e32ee3ab5841'), editable=False, unique=True),
        ),
    ]
