# Generated by Django 4.0.6 on 2022-10-16 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0017_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('11c9f3ce-c140-4ed9-afc5-e8d7d3d913bd'), editable=False, unique=True),
        ),
    ]
