# Generated by Django 4.0.6 on 2022-10-16 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0018_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('8eff8bbb-d71e-4908-a11f-9504a3b4dd5e'), editable=False, unique=True),
        ),
    ]
