# Generated by Django 4.0.6 on 2023-01-17 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0019_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('e0c01b54-f868-4d0c-83f0-3b05e5776406'), editable=False, unique=True),
        ),
    ]
