# Generated by Django 4.0.6 on 2023-01-22 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0020_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('790c00fe-c77a-4854-9d1a-c933f4c55fa8'), editable=False, unique=True),
        ),
    ]
