# Generated by Django 4.0.6 on 2023-02-12 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0021_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('7901b8b1-ea10-4c12-bcdc-c2db3830aab6'), editable=False, unique=True),
        ),
    ]
