# Generated by Django 4.0.6 on 2023-02-12 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0022_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('102a2f16-7ceb-454e-a3df-7ba8c7cea12c'), editable=False, unique=True),
        ),
    ]
