# Generated by Django 4.0.6 on 2023-02-12 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0025_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('7281a7f9-44fd-49bf-9470-94859ff7986e'), editable=False, unique=True),
        ),
    ]
