# Generated by Django 4.0.6 on 2023-02-14 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0026_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('0ac9d250-8992-4359-8bd5-e9b02f58b2b5'), editable=False, unique=True),
        ),
    ]
