# Generated by Django 4.0.6 on 2023-02-19 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0029_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('c6c74272-7072-4c63-a78d-e0b4a344f7ce'), editable=False, unique=True),
        ),
    ]
