# Generated by Django 4.0.6 on 2023-02-23 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0031_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('a9903733-6ca4-485d-8dd2-8edfe79c709a'), editable=False, unique=True),
        ),
    ]
