# Generated by Django 4.0.6 on 2023-02-23 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0032_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('cd9ba9fd-f388-489c-9ec0-7842e7b19556'), editable=False, unique=True),
        ),
    ]
