# Generated by Django 4.0.6 on 2023-02-24 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0033_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('a500093d-9d94-46ca-801f-6743251f0c25'), editable=False, unique=True),
        ),
    ]
