# Generated by Django 4.0.6 on 2023-03-07 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0036_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('6e650975-d04f-43b9-ba43-6148bc3e6680'), editable=False, unique=True),
        ),
    ]
