# Generated by Django 4.0.6 on 2023-03-07 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0038_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('bd54334a-c656-4473-9d15-f522dfc230b2'), editable=False, unique=True),
        ),
    ]
