# Generated by Django 4.0.6 on 2023-03-25 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0039_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('0d08106f-d947-4c5d-b453-4807eb2b0048'), editable=False, unique=True),
        ),
    ]
