# Generated by Django 4.0.6 on 2023-05-07 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0042_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('5a7b5af0-79c9-4dcd-adba-54a5ed7cc91f'), editable=False, unique=True),
        ),
    ]
