# Generated by Django 4.0.6 on 2023-05-09 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0045_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('dd04b771-3f87-493e-abd9-d77d891e981d'), editable=False, unique=True),
        ),
    ]
