# Generated by Django 4.0.6 on 2023-05-22 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0046_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('51511b0c-938f-4c70-a82e-6088887a1573'), editable=False, unique=True),
        ),
    ]
