# Generated by Django 4.0.6 on 2023-06-14 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0047_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('3019dde4-3c4d-43b1-ade1-74fa50acc23a'), editable=False, unique=True),
        ),
    ]
