# Generated by Django 4.2 on 2023-05-22 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0048_alter_task_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('aa8e7506-7675-4f52-bdf8-152ece0fa0bf'), editable=False, unique=True),
        ),
    ]
