# Generated by Django 3.2.8 on 2021-10-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211016_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageddevice',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='user_allocated',
            field=models.CharField(max_length=70),
        ),
    ]
