# Generated by Django 3.2.8 on 2021-10-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211016_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(default='wewerddf3w324', max_length=70),
            preserve_default=False,
        ),
    ]
