# Generated by Django 3.2.8 on 2021-10-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_member_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamlead',
            old_name='uniqid',
            new_name='user_uniqid',
        ),
    ]
