# Generated by Django 3.2.8 on 2021-10-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_uniqid_teamlead_user_uniqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damageddevice',
            name='team_allocated',
        ),
    ]
