# Generated by Django 3.2.8 on 2021-10-17 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_damageddevice_team_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('a8a3c20c-d336-411c-bfc7-3b0b66948432'), max_length=70),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('eb718807-63e6-4f5c-ab52-405edf134325'), max_length=70),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('f73cd522-f73e-4a37-9303-42efefaa8d15'), max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ac70a82b-1b8e-4e1f-870a-3d11c9b58f8a'), max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('19c6c0d1-8b09-420f-ba32-57edeefff846'), max_length=70),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('57e57109-0cd6-41b7-a93e-db5d3e8bd793'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('a154a066-2b13-4112-8875-701a01717aec'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.CharField(default=uuid.UUID('841f68e0-9155-4d44-8c31-cd7bca18cfbf'), max_length=70),
        ),
    ]
