# Generated by Django 3.2.8 on 2021-10-19 01:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20211018_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageddevice',
            name='complainant_team',
            field=models.CharField(default='wewerddf3w324', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ff603237-4cbd-4063-b80c-1d81e9559c5d'), max_length=70),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('b7599d37-3d6b-4640-bd65-a4aa4679d96f'), max_length=70),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('c6577d53-5cb4-4ba4-8624-6dcddcae06a3'), max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('e0dfd275-5bd7-4cd6-9c30-eee0c8261bfa'), max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('d604a1bf-bb75-491a-8c92-d1b51d9161c6'), max_length=70),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('e30b170b-d022-4e40-a32d-9789912149fd'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('2744de30-8d60-4c93-ac68-1bd596073e2a'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.CharField(default=uuid.UUID('218961cb-855e-4a75-a6ba-b9f1e7028cc6'), max_length=70),
        ),
    ]
