# Generated by Django 3.2.8 on 2021-10-19 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20211019_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('6fc38d05-0e51-4688-9646-671f3da092c9'), max_length=70),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('7cc1dae2-fe0e-4ca9-b363-1d704ee95ba8'), max_length=70),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ddc303cb-877f-4a34-9c0c-1a82ca67afe6'), max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('52e48234-d859-4ff6-bab4-f74bb7c404f2'), max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('763069a1-36ba-4abc-afb0-3a5b052b7b36'), max_length=70),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('5b5b08d7-f118-4920-9bef-07494d2cb629'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ea3cf5bc-0568-431c-ba18-9704a9504790'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.CharField(default=uuid.UUID('e3ea342e-7ee8-4ba7-9661-5b30911c5160'), max_length=70),
        ),
    ]
