# Generated by Django 3.2.8 on 2021-10-19 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20211019_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('9014bb3e-8f45-413a-94c6-6de935cd050f'), max_length=70),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('1f358617-380e-462a-a014-afe30524a0d2'), max_length=70),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('a8fb82fe-7d85-4917-b52b-4f63cac2d8ea'), max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('27a9e00e-35cb-44c2-8886-3b13c4cd3ef2'), max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ba1edcd2-7d42-4a7a-a75c-2e5437de5439'), max_length=70),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('17caeacc-0b88-4dfb-92d7-9bcc5a5e5c09'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('e7a24e43-71f3-4bab-b4af-002053a2b3bf'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.CharField(default=uuid.UUID('6bc16640-d616-4c20-a398-c591a9ba6b13'), max_length=70),
        ),
    ]
