# Generated by Django 3.2.8 on 2021-10-19 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20211019_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='team',
            field=models.CharField(default='team', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('d48843bf-69eb-4ca3-90f0-43959a7cc707'), max_length=70),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('6a009a81-4787-4cc3-b30f-3687108d67d0'), max_length=70),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('7e8b7216-9104-4062-a97c-2be64dcf80b3'), max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('97a858b7-12d5-4aed-b10e-9a02d58ca8e3'), max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('65b6d71b-d080-4298-aeea-7122f670bbb0'), max_length=70),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('2e246ff3-af57-4b3e-b68c-36b8f8602aee'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('c9cbf70e-7536-4215-87c8-7d38317aff60'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.CharField(default=uuid.UUID('3a9b7986-c168-4664-bab5-0a3d063519ba'), max_length=70),
        ),
    ]
