# Generated by Django 3.2.8 on 2021-10-19 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20211019_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('7ebeb8b1-8e63-4da2-a182-0d0424675b92'), max_length=70),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('aa14702a-884b-44af-87e1-7f50f94362fd'), max_length=70),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('7a1c461b-2975-4b9f-8a94-0313c266c577'), max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('fe0a44d2-f0e5-4c69-92e7-47a2a5196d81'), max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('5e05b167-47fe-4ed4-88aa-9714f9cbc30d'), max_length=70),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('5caa2a05-c73e-423c-ac7f-22b7a535d7aa'), max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('e8894faa-50b9-446d-a071-0d6eefea149b'), max_length=70),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.CharField(default=uuid.UUID('9b029535-1e4d-463b-b08f-c2abb0d66575'), max_length=70),
        ),
    ]
