# Generated by Django 3.2.8 on 2021-10-19 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20211019_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('b3ac2574-6560-4a58-9d93-62dc34dcecca'), max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
