# Generated by Django 3.2.8 on 2021-10-19 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_team_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('0e19e213-afc7-4230-8d86-f569b9908a4b'), unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
