# Generated by Django 3.2.8 on 2021-10-19 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20211019_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('e9139875-6683-440f-a7ab-b89630a9b190'), editable=False, unique=True),
        ),
    ]
