# Generated by Django 3.2.8 on 2021-12-13 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='device_uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='device_uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('427acb02-e2af-4e31-ba84-4b2bba4b18cc'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='device_uniqid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
