# Generated by Django 3.2.8 on 2021-12-13 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20211213_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='device_uniqid',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='device_uniqid',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.UUIDField(default=uuid.UUID('a5476f8c-2433-4ad9-b395-eee7d42b6739'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='device_uniqid',
            field=models.CharField(max_length=70),
        ),
    ]
