# Generated by Django 3.2.8 on 2021-12-13 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20211213_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='uniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='damageddevice',
            name='uniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('55e7acb8-0ea7-4e90-b220-8e5603a3ffcd'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='uniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='teamallocation',
            name='uniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='user_uniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
    ]
