# Generated by Django 4.0.2 on 2022-06-03 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20211213_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('e014ab44-c162-42f8-9fa6-3d6acb9b8440'), editable=False, max_length=35, unique=True),
        ),
    ]
