# Generated by Django 4.0.2 on 2022-06-03 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('20504c82-4a15-4d59-8275-f84e8e31ee04'), editable=False, max_length=35, unique=True),
        ),
    ]
