# Generated by Django 4.0.2 on 2022-06-03 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('d522d371-7ea3-4767-9675-3a01e96cde6d'), editable=False, max_length=35, unique=True),
        ),
    ]
