# Generated by Django 4.0.6 on 2022-07-06 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_device_uniqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fullname',
            field=models.CharField(default='tester', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('1fdafc07-e2cb-414b-b1b1-8af3492d859d'), editable=False, max_length=35, unique=True),
        ),
    ]
