# Generated by Django 4.0.6 on 2022-07-06 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_member_fullname_alter_device_uniqid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('4d8ab667-3699-4112-b45c-57c00c4c8573'), editable=False, max_length=35, unique=True),
        ),
    ]
