# Generated by Django 4.0.6 on 2022-07-07 22:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0029_alter_device_uniqid_alter_member_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenStore',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uniqid', models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True)),
                ('access_token', models.CharField(max_length=70)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('c79f2528-8b74-4469-8353-93c49b607fc6'), editable=False, max_length=35, unique=True),
        ),
    ]
