# Generated by Django 4.0.6 on 2022-07-12 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='poster',
            field=models.ImageField(null=True, upload_to='', verbose_name='images/'),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('d6a2ef68-8187-4f8c-ae7f-86df9ace20ca'), editable=False, max_length=35, unique=True),
        ),
    ]
