# Generated by Django 4.0.6 on 2022-07-24 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_device_poster_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('4a22f5c6-de86-4561-a0ba-1807c2bd8ad3'), editable=False, max_length=35, unique=True),
        ),
    ]
