# Generated by Django 4.0.6 on 2022-08-02 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_allocation_user_team_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('63952ea4-0379-41fb-8c1d-a8e140f6e561'), editable=False, max_length=35, unique=True),
        ),
    ]
