# Generated by Django 4.0.6 on 2022-08-02 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('327f5aac-c30f-45ce-8b0e-30c651850a98'), editable=False, max_length=35, unique=True),
        ),
    ]
