# Generated by Django 4.0.6 on 2022-08-02 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_alter_device_uniqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='user_team',
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('87f47a48-e047-4558-a93e-a5f8c8cbe4ce'), editable=False, max_length=35, unique=True),
        ),
    ]
