# Generated by Django 4.0.6 on 2022-08-02 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_remove_allocation_user_team_alter_device_uniqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='user_team',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('eb6be09c-cdbc-4353-a68a-26ef58effcd4'), editable=False, max_length=35, unique=True),
        ),
    ]
