# Generated by Django 4.0.6 on 2022-08-07 15:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_allocation_user_team_alter_device_uniqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageddevice',
            name='user_uniqid',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('8366b1a6-706f-4add-becc-c5e103416bc4'), editable=False, max_length=35, unique=True),
        ),
    ]
