# Generated by Django 4.0.6 on 2022-10-16 11:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_damageddevice_user_uniqid_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('37fd1f32-1eb7-4f52-aabc-859284959328'), editable=False, max_length=35, unique=True),
        ),
    ]
