# Generated by Django 4.0.6 on 2023-01-22 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_teamallocation_status_alter_device_uniqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('0f6bec02-8abe-445f-a265-a30c1c315198'), editable=False, max_length=35, unique=True),
        ),
    ]
