# Generated by Django 4.0.6 on 2023-02-12 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_allocation_status_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('21a2bbf7-5607-410a-9c10-fe0c955d3145'), editable=False, max_length=35, unique=True),
        ),
    ]
