# Generated by Django 4.0.6 on 2023-02-12 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_device_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ad1d6af5-7e96-4882-8b2e-982eb67d0da6'), editable=False, max_length=35, unique=True),
        ),
    ]
