# Generated by Django 4.0.6 on 2023-02-12 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_alter_device_uniqid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('resetUniqid', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('64d6b6f5-bff8-497a-bc4c-52af5ef0b2c4'), editable=False, max_length=35, unique=True),
        ),
    ]
