# Generated by Django 4.0.6 on 2023-02-14 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_alter_device_uniqid_alter_resetpassword_resetuniqid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=70)),
                ('uniqid', models.CharField(default=uuid.UUID('214294d0-e6d2-407a-bfd5-384d36e5b7c7'), editable=False, max_length=35, unique=True)),
                ('link', models.CharField(max_length=70)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('bb66c64b-5bb7-42f1-8a3c-c7bb9263a192'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='resetUniqid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=35, unique=True),
        ),
    ]
