# Generated by Django 4.0.6 on 2023-02-23 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0053_alter_device_uniqid_alter_devicetype_uniqid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('765df278-dcbc-45dd-810a-115a5dbbafce'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('cd575a6b-a8a4-41d5-9368-6b842bb79be9'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('5314e93c-c9e2-47e7-b559-21b29d184f52'), editable=False, max_length=35, unique=True),
        ),
    ]
