# Generated by Django 4.0.6 on 2023-02-23 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_alter_device_uniqid_alter_devicetype_uniqid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('e5b7f7be-024a-4de8-b756-5a9a36c5f549'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('641c43f9-5cbd-4224-8499-e54fce73bc07'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('535a10c8-ec72-467d-8b48-50522198e2fa'), editable=False, max_length=35, unique=True),
        ),
    ]
