# Generated by Django 4.0.6 on 2023-02-24 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_rename_assigned_status_device_resource_assigned_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='poster',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='poster_link',
            field=models.CharField(default='link', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('c2282920-069a-44b4-abd8-57c1b35926bd'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('bd9c7fc5-2ae5-4ec9-860b-c523ec6ac7f7'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('71806d78-ff2f-42de-b9d2-a21495a3866a'), editable=False, max_length=35, unique=True),
        ),
    ]
