# Generated by Django 4.0.6 on 2023-03-07 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_remove_devicetype_poster_devicetype_poster_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('783a94bc-8cae-4bea-8e95-076aafc79c51'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('44180570-fee8-46ac-bcda-ce9f687c9eaa'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('72bec694-020c-488b-9bdd-ac33f911bb34'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='uniqid',
            field=models.CharField(editable=False, max_length=35, unique=True),
        ),
    ]
