# Generated by Django 4.0.6 on 2023-03-07 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0060_alter_device_uniqid_alter_devicetype_uniqid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uniqid',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ebd23f61-6836-4bfa-90b0-792bc7b6f1fb'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('6b93b907-7b8d-4fcd-9bdb-2725f0c91275'), editable=False, max_length=35, unique=True),
        ),
    ]
