# Generated by Django 4.0.6 on 2023-03-25 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_alter_device_uniqid_alter_devicetype_uniqid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='poster_link',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('600c8a59-65ee-40c2-80a0-523153547c48'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('09d74a41-9b27-465f-a3df-780e8f2020f1'), editable=False, max_length=35, unique=True),
        ),
    ]
