# Generated by Django 4.0.6 on 2023-05-05 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_alter_devicetype_uniqid_alter_notification_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='use',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('0f3dde83-9e95-471a-a89b-335fc45a3810'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('44311057-01ab-4ca4-b95a-dd5864571a85'), editable=False, max_length=35, unique=True),
        ),
    ]
