# Generated by Django 4.0.6 on 2023-05-07 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0064_alter_allocation_use_alter_devicetype_uniqid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('ef19972e-acf1-465b-ad6d-4e26cd05534e'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('3c5021cd-e03d-45c3-85f7-2cf9841fdd53'), editable=False, max_length=35, unique=True),
        ),
    ]
