# Generated by Django 4.0.6 on 2023-05-09 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_alter_device_serial_number_alter_devicetype_uniqid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('d7fe62df-9447-439e-bbe4-3685a40f4c68'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('0757f883-5831-46ca-9315-5ce0c3268b50'), editable=False, max_length=35, unique=True),
        ),
    ]
