# Generated by Django 4.2 on 2023-05-22 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0069_returntooffice_alter_devicetype_uniqid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('58caf7e2-f9ff-4ef9-8150-46d28f12af29'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('d0a2d079-1452-4a3c-84a1-afab9a85f751'), editable=False, max_length=35, unique=True),
        ),
    ]
