# Generated by Django 4.2 on 2023-05-22 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_alter_devicetype_uniqid_alter_notification_uniqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returntooffice',
            name='allocation_uniqid',
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('a2c91612-2efd-41a4-8b7f-f1cc2071bb2b'), editable=False, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uniqid',
            field=models.CharField(default=uuid.UUID('a7429bf1-edb1-4dbf-aa7e-cbb6f1c08c7b'), editable=False, max_length=35, unique=True),
        ),
    ]
